### ISSUE TITLE
Curve handles not working

### ISSUE THREAD

**Issue by felipedelrio** [Mets3D/CloudRig#1]
Hi Mets

I've been playing with the package, but it seems like the actual release isn't working like in the tutorial.

This is what I get when running "Generate CloudRig":
Some bones that I think should be hidden are visible in all layers.

![1](https://user-images.githubusercontent.com/26682533/81491039-7cb4e600-925f-11ea-95c1-1086713f52cf.jpg)

Also, handles are not working when using the cloud_curve rig type:

![2](https://user-images.githubusercontent.com/26682533/81491106-68bdb400-9260-11ea-8acc-8eed5ea1e4c4.jpg)

I used the last Blender 2.83 beta release, ce76e17584ee.

![3](https://user-images.githubusercontent.com/26682533/81491202-bf77bd80-9261-11ea-903e-2b5347936b8c.jpg)

Anyway, thanks for the great improvements in rigify, it'll be very useful :)

**Comment by Mets3D** [comment]
Thanks, these should be fixed now! Let me know otherwise.
